server:
  port: 9090
  error:
    include-message: always
  servlet:
    context-path: /api
spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/blog_comments
    username: root
    password : root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  properties:
    hibernate:
      dialect : org.hibernate.dialect.MySQL5Dialect
      format_sql : true
